sudo: required
services:
    - docker

before_install:
    - docker build -t ankitb8/docker-react -f dockerfile.dev .

script:
    - docker run -e CI=true ankitb8/docker-react npm run test

# Deploy to AWS Elastic Bean Stalk
#deploy:
#    edge: true
#    provider: elasticbeanstalk
#    region: "us-east-1"
#    app: "docker-react"
#    env: "DockerReact-env"
#    bucket_name: "elasticbeanstalk-us-east-1-398503328169"
#    bucket_path: "docker-react"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY